# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6780aaa6119bd2bcc42871839ffc807a12b6fdee93b653d2ba2cadf4d39871353bbb431e8fff0e6803039fa475829a7fc2507efc3df09e80f88d61c66027edc5

test:
  secret_key_base: bfeb7cbc1a3eb129117162220828df5eabf6b2abb89d34163b098e2a601935bc390e6e0e84e6695170ee5c49921a997a24a3d5b3dac8a399ce570d68f021f5b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
